name: Deploy Java8

on:
  push:
    branches:
      - develop
    paths:
      - 'java8/**'
      - 'Makefile'
      - '.github/workflows/java8*'

jobs:
  deploy_java8:
    runs-on: ubuntu-latest
    container:
      image: bananawhite98/ubuntu:1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Java8
        run: |
          cd java8
          make -C ../. build-java8 VERSION=1 DIR=java8
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          make -C ../. push-java8 VERSION=1
      - name: Cleanup
        run: |
          cd java8
          make -C ../. rmi-java VERSION=1