name: Deploy Java17

on:
  push:
    branches:
      - develop
    paths:
      - 'java17/**'
      - 'Makefile'
      - '.github/workflows/java17*'

jobs:
  deploy_java17:
    runs-on: ubuntu-latest
    container:
      image: bananawhite98/ubuntu:1
    env:
      JAVA_VERSION: 17
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Java17
        run: |
          cd java${{ env.JAVA_VERSION }}
          make -C ../. build-java${{ env.JAVA_VERSION }} VERSION=1 DIR=java${{ env.JAVA_VERSION }}
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          make -C ../. push-java${{ env.JAVA_VERSION }} VERSION=1
      - name: Cleanup
        run: |
          cd java${{ env.JAVA_VERSION }}
          make -C ../. rmi-java${{ env.JAVA_VERSION }} VERSION=1