name: Java8 Test

on:
  pull_request:
    paths:
      - 'java8/**'
      - 'Makefile'
      - '.github/workflows/java8*'
      - 'java_files/**'

jobs:
  test_build_java8:
    runs-on: ubuntu-latest
    container:
      image: bananawhite98/ubuntu:1
    env:
      JAVA_VERSION: 8
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Java8
        run: |
          cd java${{ env.JAVA_VERSION }}
          make -C ../. build-java${{ env.JAVA_VERSION }} VERSION=test DIR=java${{ env.JAVA_VERSION }}
      - name: Cleanup
        run: |
          cd java${{ env.JAVA_VERSION }}
          make -C ../. rmi-java${{ env.JAVA_VERSION }} VERSION=test