name: Check modifying GitHub pages entry.

on:
  pull_request:
    paths:
      - '.github/workflows/update-github-pages-test.yml'

jobs:
  create-entry:
    runs-on: ubuntu-latest

    steps:
      - name: Github pages
        uses: actions/checkout@v2
        with:
          repository: rszewczyk2204/rszewczyk2204.github.io
          ref: refs/heads/main

      - name: Clone repo
        run: |
          cd /home/runner/work
          git clone ${{ secrets.PAGES_REPO_GIT }}
          cd ${{ secrets.REPO_NAME }}

      - name: Put entry in github pages
        run: |
          cd /home/runner/work/${{ secrets.REPO_NAME }}
          chmod 777 index.html
          if ! grep -q '<a href="#" class="repo-link">docker-images</a>' index.html; then
          echo "Repo entry not found, adding it..."
          sed -i '/<section class="repos">/,/<\/section>/ s~<\/section>~ \
                      <div class="repo-item"> \
                          <h4 class="h4"><a href="https://github.com/rszewczyk2204/docker-images" class="repo-link">docker-images</a></h4> \
                          <button class="expand-repo-button" data-expand-button> \
                              <span>docker-images</span> \
                              <ion-icon name="chevron-down"></ion-icon> \
                          </button> \
                          <div data-expand-info="docker-images" class="expand-repo-info"> \
                              <span>Repo containing docker images to run more advanced GitHub actions. \
                              </span> \
                          </div> \
                      </div> \
                      <div class="separator"></div> \
                  </section>~' index.html
          git status
          else
            echo "Repo entry already exists."
          fi

      - name: Cleanup
        run: |
          rm -rf /home/runner/work/${{ secrets.REPO_NAME }}